# The next line is used by Flutter to locate generated config file.
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/\AFLUTTER_ROOT=(.*)\z/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'xcode_backend.rb'), flutter_root) if File.exist?(File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'xcode_backend.rb'), flutter_root))

generated_podhelper_path = File.expand_path(File.join('..', 'Flutter', 'generated_podhelper.rb'), __FILE__)
if File.exist?(generated_podhelper_path)
  load generated_podhelper_path
end

platform :ios, '13.0'

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  if defined?(flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.expand_path(File.join('..', 'Flutter'), __FILE__)
  end

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if defined?(flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

