# The next line is used by Flutter to locate generated config file.
generated_podhelper_path = File.expand_path(File.join('..', 'Flutter', 'generated_podhelper.rb'), __FILE__)
if File.exist?(generated_podhelper_path)
  load generated_podhelper_path
end

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  if respond_to?(:flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.expand_path(File.join('..', 'Flutter'), __FILE__)
  end

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if respond_to?(:flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end
    
    # Fix for GoogleUtilities/UserDefaults conflict and other common issues
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

