# The next line is used by Flutter to locate generated config file.
load File.expand_path(File.join('..', 'Flutter', 'generated_podhelper.rb'), __FILE__)

platform :ios, '13.0'

# CocoaPods platforms which tend to use the latest SDK.
# platform :ios, '11.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path(File.join('..', 'Flutter'), __FILE__)

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Fix for GoogleUtilities/UserDefaults conflict and other common issues
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

